spring.application.name=producer-service
# Server port for the producer application
server.port=8080

# Kafka Producer Configuration
# We are connecting to the LOCAL Kafka cluster
spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Topic name
app.topic.name=orders